version: '3.8'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  webserver:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    image: nginx-server
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
